# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows or borders
    # gaps_in = 0
    # gaps_out = 0
    # border_size = 0

    # Change to niri-like side-scrolling layout
    # layout = scrolling
    border_size = 0
    col.active_border = 0xffe2e2e3

    # Tighter gap under the waybar; sides/bottom unchanged (top, right, bottom, left)
    gaps_out = 5, 10, 10, 10
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 0

    # Dim unfocused windows (0.0 = no dim, 1.0 = fully dimmed)
    # dim_inactive = true
    # dim_strength = 0.15

    # Transparency on windows
    active_opacity = 0.95
    inactive_opacity = 0.88

    blur {
        enabled = true
        size = 6
        passes = 2
        special = true
        brightness = 0.60
        contrast = 0.75
    }
}

# https://wiki.hyprland.org/Configuring/Variables/#animations
animations {
    # Disable all animations
    # enabled = no

    # Instant window transitions (including fullscreen)
    animation = windows, 1, 1, default
}

# https://wiki.hypr.land/Configuring/Variables/#group
group {
    auto_group = false
    col.border_active = rgb(7c3aed)
    col.border_inactive = rgba(7c3aed40)

    groupbar {
        render_titles = true
        font_size = 10
        height = 18
        indicator_height = 0
        indicator_gap = 5
        gaps_in = 5
        gaps_out = 0
        text_color = rgb(ffffff)
        text_color_inactive = rgba(ffffff90)
        col.active = rgba(7c3aed90)
        col.inactive = rgba(00000020)
        gradients = true
        gradient_rounding = 0
    }
}

# https://wiki.hypr.land/Configuring/Variables/#layout
layout {
    single_window_aspect_ratio = 16 10
}
